steps:
# Install
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
# Build
- name: 'gcr.io/cloud-builders/mvn'
  args: ['run', 'build']
# Deploy
- name: 'gcr.io/my-springboot-app/firebase'
  args: ['deploy']